import * as Location from "expo-location";
import { useState } from "react";
import { Alert, Pressable, SafeAreaView, StyleSheet, Text, View } from "react-native";
type Step = "offered"|"driver_en_route_to_pickup"|"collected"|"driver_en_route"|"nearby"|"delivered";
const next: Record<Step, Step | null> = { offered:"driver_en_route_to_pickup", driver_en_route_to_pickup:"collected", collected:"driver_en_route", driver_en_route:"nearby", nearby:"delivered", delivered:null };
export default function DriverHome(){ const [available,setAvailable]=useState(true); const [step,setStep]=useState<Step>("offered"); const [sharing,setSharing]=useState(false); const [permission,setPermission]=useState("Location not shared");
 const startSharing=async()=>{ const response=await Location.requestForegroundPermissionsAsync(); if(response.status!=="granted"){setPermission("GPS permission denied — manual status updates still work");return;} setSharing(true);setPermission("Simulated location sharing active (Demo)"); };
 const advance=()=>{ const destination=next[step]; if(!destination)return; if(destination==="delivered") Alert.alert("Proof required","Demo proof: handed to customer will be recorded.",[{text:"Record proof & finish",onPress:()=>{setStep(destination);setSharing(false);setPermission("Location sharing stopped");}}]); else setStep(destination);};
 return <SafeAreaView style={s.screen}><View style={s.badge}><Text style={s.badgeText}>DEMO — NO LIVE GPS</Text></View><Text style={s.title}>Driver home</Text><Pressable onPress={()=>setAvailable(!available)} style={[s.availability,available?s.available:s.offline]}><Text style={s.buttonText}>{available?"Available":"Offline"}</Text></Pressable><View style={s.card}><Text style={s.label}>ACTIVE JOB OFFER</Text><Text style={s.order}>TWK-DEMO-1042</Text><Text style={s.copy}>Pickup: Tunbridge Wells Kebab</Text><Text style={s.copy}>Delivery destination becomes visible after accepting this job.</Text><Text style={s.status}>{step.replaceAll("_"," ")}</Text><Pressable onPress={advance} style={s.action}><Text style={s.actionText}>{step==="offered"?"Accept & travel to pickup":step==="delivered"?"Delivery completed":`Mark ${next[step]?.replaceAll("_"," ")}`}</Text></Pressable></View><View style={s.card}><Text style={s.label}>LOCATION SHARING</Text><Text style={s.copy}>Your location is shared only with the assigned customer and owner while you choose to share an active delivery. It stops when you finish or tap Stop sharing.</Text><Text style={s.copy}>{permission}</Text>{!sharing?<Pressable onPress={startSharing} style={s.secondary}><Text>Start sharing for delivery</Text></Pressable>:<Pressable onPress={()=>{setSharing(false);setPermission("Location sharing stopped");}} style={s.stop}><Text style={s.buttonText}>Stop sharing</Text></Pressable>}</View></SafeAreaView>; }
const s=StyleSheet.create({screen:{flex:1,backgroundColor:"#101822",padding:20,gap:14},badge:{alignSelf:"flex-start",backgroundColor:"#d73921",padding:6},badgeText:{fontWeight:"800",color:"white",fontSize:12},title:{fontSize:34,fontWeight:"800",color:"white"},availability:{padding:15,borderRadius:5,alignItems:"center"},available:{backgroundColor:"#387d4e"},offline:{backgroundColor:"#65707d"},buttonText:{color:"white",fontWeight:"800",fontSize:16},card:{backgroundColor:"#fffdf7",borderRadius:6,padding:18,gap:10},label:{color:"#d73921",fontWeight:"800",fontSize:12},order:{fontSize:24,fontWeight:"800"},copy:{fontSize:16,lineHeight:23},status:{fontSize:16,fontWeight:"700",textTransform:"capitalize"},action:{backgroundColor:"#d73921",padding:15,alignItems:"center",borderRadius:4},actionText:{color:"white",fontSize:16,fontWeight:"800"},secondary:{padding:13,backgroundColor:"#f4b727",alignItems:"center",borderRadius:4},stop:{padding:13,backgroundColor:"#101822",alignItems:"center",borderRadius:4}});
