import { createClient } from "https://esm.sh/@supabase/supabase-js@2.97.0";
import { json, options, requireEnv } from "../_shared/http.ts";
type Input = { mode: "demo" | "live"; reason: string; confirmed: boolean };
Deno.serve(async (request) => { if (request.method === "OPTIONS") return options(); if (request.method !== "POST") return json({ error:"Method not allowed" },405); try {
 const authorization=request.headers.get("Authorization"); if(!authorization)return json({error:"Sign in required"},401); const url=requireEnv("SUPABASE_URL"), key=requireEnv("SUPABASE_PUBLISHABLE_KEY"), service=requireEnv("SUPABASE_SERVICE_ROLE_KEY");
 const userClient=createClient(url,key,{global:{headers:{Authorization:authorization}}}); const {data:{user}}=await userClient.auth.getUser(); if(!user)return json({error:"Invalid session"},401); const admin=createClient(url,service,{auth:{persistSession:false}});
 const {data:roles}=await admin.from("user_roles").select("role").eq("user_id",user.id); if(!roles?.some(r=>r.role==="owner"))return json({error:"Owner permission required"},403); const input=await request.json() as Input; if(!input.reason?.trim())return json({error:"A reason is required"},400);
 const blockers:string[]=[]; if(input.mode==="live"){if(!input.confirmed) blockers.push("Owner confirmation / re-authentication is required"); for(const name of ["STRIPE_SECRET_KEY","STRIPE_WEBHOOK_SECRET","MAPBOX_DIRECTIONS_TOKEN","TWK_APP_ORIGIN"]){if(!Deno.env.get(name))blockers.push(`${name} is not configured`);} const [{count:owners},{count:kitchens},{count:drivers},{count:zones},{count:fees},{data:restaurant}]=await Promise.all([admin.from("user_roles").select("*",{count:"exact",head:true}).eq("role","owner"),admin.from("user_roles").select("*",{count:"exact",head:true}).eq("role","kitchen"),admin.from("user_roles").select("*",{count:"exact",head:true}).eq("role","driver"),admin.from("delivery_zones").select("*",{count:"exact",head:true}).eq("is_available",true),admin.from("fee_policies").select("*",{count:"exact",head:true}).not("published_at","is",null).is("retired_at",null),admin.from("restaurants").select("pickup_address").maybeSingle()]); if(!(owners&&owners>0))blockers.push("At least one owner is required"); if(!(kitchens&&kitchens>0))blockers.push("At least one kitchen user is required"); if(!(drivers&&drivers>0))blockers.push("At least one approved driver is required"); if(!(zones&&zones>0))blockers.push("A published delivery zone is required"); if(!(fees&&fees>0))blockers.push("A published fee policy is required"); if(!restaurant?.pickup_address||restaurant.pickup_address.includes("Demo"))blockers.push("A real restaurant pickup address is required"); }
 const {data:before}=await admin.from("runtime_configuration").select("mode").eq("singleton",true).single(); if(blockers.length){await admin.from("audit_logs").insert({actor_id:user.id,action:"live_mode_blocked",target_table:"runtime_configuration",reason:input.reason,metadata:{blocker_count:blockers.length}});return json({ok:false,blockers},409);} await admin.from("runtime_configuration").update({mode:input.mode,live_readiness_confirmed_at:input.mode==="live"?new Date().toISOString():null,live_readiness_confirmed_by:input.mode==="live"?user.id:null}).eq("singleton",true); await admin.from("audit_logs").insert({actor_id:user.id,action:"runtime_mode_changed",target_table:"runtime_configuration",reason:input.reason,metadata:{from:before?.mode,to:input.mode}}); return json({ok:true,mode:input.mode});
 }catch(error){console.error("set-runtime-mode failed",error instanceof Error?error.message:"unknown");return json({error:"Unable to change runtime mode"},500);}});
