"use client";
import { useMemo, useState } from "react";
import { formatMoney, quote } from "@twk/shared";

type MenuItem = { id: string; category: string; name: string; description?: string; price: number; variants?: { name: string; price: number }[] };
const menu: MenuItem[] = [
 { id:"doner", category:"Kebabs", name:"Doner Kebab", description:"Served in pitta & salad.", price:800, variants:[{name:"Medium",price:800},{name:"Large",price:1000}] },
 { id:"chicken-shish", category:"Kebabs", name:"Chicken Shish Kebab", description:"Marinated chicken grilled on skewers.", price:900, variants:[{name:"Medium",price:900},{name:"Large",price:1250}] },
 { id:"super-best", category:"Kebabs", name:"Super Best", description:"Shish, chicken, kofte, doner & chips.", price:2500 },
 { id:"lamb-doner", category:"Combination Kebabs", name:"Lamb Shish & Doner", description:"Served with pitta bread & salad.", price:1250 },
 { id:"burger", category:"Burgers", name:"Chicken Burger", description:"Served with salad garnish.", price:550 },
 { id:"twister", category:"Meals", name:"Chicken Twister meal", description:"Chicken Twister, chips & drink.", price:1100 },
 { id:"wings", category:"Chicken", name:"8 Chicken Wings With Chips", description:"Grilled.", price:900 },
 { id:"cod", category:"Fish", name:"Cod & Chips", price:850 },
 { id:"humus", category:"Starters", name:"Humus", price:500 }
];
type BasketLine = MenuItem & { selectedPrice: number; variant?: string; quantity: number };
export default function Home() {
 const [type, setType] = useState<"delivery"|"collection">("delivery"); const [basket, setBasket] = useState<BasketLine[]>([]); const [view, setView] = useState<"menu"|"checkout"|"track"|"kitchen"|"owner">("menu"); const [status, setStatus] = useState("paid");
 const food = basket.reduce((total,line)=>total + line.selectedPrice * line.quantity,0); const totals = quote(food,type); const categories = [...new Set(menu.map(i=>i.category))];
 const add = (item:MenuItem, price = item.price, variant?:string) => setBasket(lines => { const found=lines.find(l=>l.id===item.id && l.variant===variant); return found ? lines.map(l=>l===found?{...l,quantity:l.quantity+1}:l) : [...lines,{...item,selectedPrice:price,variant,quantity:1}]; });
 const update = (index:number,delta:number) => setBasket(lines=> lines.flatMap((line,i)=>i===index ? line.quantity+delta>0?[{...line,quantity:line.quantity+delta}]:[]:[line]));
 if (view === "checkout") return <main><Top setView={setView}/><section className="checkout"><div><span className="eyebrow">Demo checkout</span><h1>Review your order</h1><p className="allergy">Please contact the takeaway before ordering if you have an allergy. Ingredients and cross-contamination information must be confirmed by the merchant.</p><label>Name<input defaultValue="Demo Customer" /></label><label>Phone<input defaultValue="07123 456789" /></label>{type==="delivery"&&<label>Delivery address<input defaultValue="Demo address — not sent anywhere" /></label>}<button className="primary" onClick={()=>setView("track")}>Confirm fake payment · {formatMoney(totals.totalPence)}</button><p className="muted">Demo only — no payment is taken and nobody is notified.</p></div><Receipt basket={basket} totals={totals}/></section></main>;
 if (view === "track") return <main><Top setView={setView}/><section className="track"><span className="eyebrow">Demo order · TWK-DEMO-1042</span><h1>Your order is {status.replaceAll("_"," ")}</h1><div className="map"><div className="restaurant">TWK<br/><small>Pickup</small></div><div className="driver">●</div><div className="destination">Your delivery<br/>destination</div><p>Simulated driver location</p></div><div className="timeline">{["paid","confirmed","preparing","ready_for_pickup","driver_assigned","driver_en_route","delivered"].map(s=><button key={s} className={s===status?"active":""} onClick={()=>setStatus(s)}>{s.replaceAll("_"," ")}</button>)}</div><p className="muted">The map is simulated in Demo. A live point is only labelled live when it is under 90 seconds old.</p></section></main>;
 if (view === "kitchen") return <main><Top setView={setView}/><section className="ops"><span className="eyebrow">Kitchen · Demo</span><h1>Today’s queue</h1><article><b>TWK-DEMO-1042</b><p>Chicken Twister meal × 1 · Delivery</p><div className="actions"><button onClick={()=>setStatus("confirmed")}>Accept</button><button onClick={()=>setStatus("preparing")}>Preparing</button><button onClick={()=>setStatus("ready_for_pickup")}>Ready for pickup</button></div></article></section></main>;
 if (view === "owner") return <main><Top setView={setView}/><section className="ops"><span className="eyebrow">Owner control centre · Demo locked</span><h1>Dispatch & readiness</h1><div className="grid"><article><b>Ready / unassigned</b><p>TWK-DEMO-1042</p><button onClick={()=>setStatus("driver_assigned")}>Assign demo driver</button></article><article><b>Live mode blockers</b><ul><li>Stripe and signed webhook</li><li>Restricted maps configuration</li><li>Terms, privacy & support links</li><li>Approved driver GPS test</li></ul><button disabled>Live mode stays locked</button></article><article><b>Audit</b><p>Demo order paid — simulated</p><p>Owner opened control centre</p></article></div></section></main>;
 return <main><Top setView={setView}/><section className="hero"><div><span className="eyebrow">Tunbridge Wells Kebab · Demo</span><h1>Proper local takeaway.<br/><em>Clear prices.</em></h1><p>Order for delivery or collection. Every fee is shown before you confirm.</p><div className="toggle"><button className={type==="delivery"?"selected":""} onClick={()=>setType("delivery")}>Delivery</button><button className={type==="collection"?"selected":""} onClick={()=>setType("collection")}>Collection</button></div></div><aside className="basket"><h2>Your basket</h2>{basket.length===0?<p className="muted">Choose something from the menu.</p>:basket.map((l,i)=><div className="line" key={`${l.id}-${l.variant}`}><span>{l.name}{l.variant&&` · ${l.variant}`}<small>× {l.quantity}</small></span><b>{formatMoney(l.selectedPrice*l.quantity)}</b><button aria-label={`Remove one ${l.name}`} onClick={()=>update(i,-1)}>−</button><button aria-label={`Add one ${l.name}`} onClick={()=>update(i,1)}>+</button></div>)}<Receipt basket={basket} totals={totals}/><button className="primary" disabled={!basket.length} onClick={()=>setView("checkout")}>Checkout</button></aside></section><section className="menu">{categories.map(category=><div key={category}><h2>{category}</h2>{menu.filter(i=>i.category===category).map(item=><article key={item.id}><div><h3>{item.name}</h3><p>{item.description}</p></div><div className="choices">{item.variants ? item.variants.map(v=><button key={v.name} onClick={()=>add(item,v.price,v.name)}>{v.name} · {formatMoney(v.price)}</button>) : <button onClick={()=>add(item)}>{formatMoney(item.price)} <span>Add</span></button>}</div></article>)}</div>)}</section></main>;
}
function Top({setView}:{setView:(v:any)=>void}) { return <header><button className="brand" onClick={()=>setView("menu")}>TWK<span>KEBAB</span></button><nav><button onClick={()=>setView("kitchen")}>Kitchen</button><button onClick={()=>setView("owner")}>Owner</button><span>DEMO</span></nav></header>; }
function Receipt({basket,totals}:{basket:BasketLine[];totals:ReturnType<typeof quote>}) { return <div className="receipt"><div><span>Food subtotal</span><b>{formatMoney(totals.foodSubtotalPence)}</b></div><div><span>Delivery or Collection</span><b>{formatMoney(totals.deliveryFeePence)}</b></div><div><span>Tunbridge Wells Kebab platform fee</span><b>{formatMoney(totals.platformFeePence)}</b></div><div><span>Transaction fee</span><b>{formatMoney(totals.transactionFeePence)}</b></div><div className="total"><span>Total</span><b>{formatMoney(totals.totalPence)}</b></div></div>; }
